# Generated by Django 3.1.3 on 2021-02-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_auto_20201229_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableQuestionResult',
            fields=[
                ('table_question_result_col_id', models.AutoField(db_column='Table_Question_Result_col_id', primary_key=True, serialize=False)),
                ('table_question_result_col_answer', models.CharField(db_column='Table_Question_Result_col_Answer', max_length=256, null=True)),
                ('table_question_result_col_marks', models.CharField(db_column='Table_Question_Result_col_Marks', max_length=256, null=True)),
                ('table_question_result_col_blank', models.CharField(db_column='Table_Question_Result_col_Blank', max_length=256, null=True)),
                ('table_question_result_col_user_id', models.CharField(db_column='Table_Question_Result_col_user_id', max_length=256, null=True)),
                ('table_question_result_col_questionaire_id', models.CharField(db_column='Table_Question_Result_col_questionaire_id', max_length=256, null=True)),
                ('table_question_result_col_question_id', models.CharField(db_column='Table_Question_Result_col_question_id', max_length=256, null=True)),
            ],
            options={
                'db_table': 'Table_Question_Result',
                'managed': True,
            },
        ),
    ]
