# Generated by Django 3.1.3 on 2021-02-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0005_tableorganization_table_organization_col_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorganization',
            name='table_organization_col_unicode',
        ),
    ]
